version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
      - ./alembic:/code/alembic
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RANDOM_RECIPE_API_KEY=${RANDOM_RECIPE_API_KEY}
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: